### ISSUE TITLE
Upgrade nom to latest release 7.1

### ISSUE THREAD

**Issue by nstinus** [baoyachi/duration-str#12]

**Comment by baoyachi** [comment]
@nstinus Thanks for your pr.Now, published new version, please use
```toml
[dependencies]
duration-str = "0.5.0"
```
